appname: "erulb"
entrypoints:
    release-host:
        privileged: true
        cmd: "nginx -p /erulb/server -c /erulb/conf/release.conf"
        ports:
            - "80/tcp"
        network_mode: "host"
    beta-host:
        privileged: true
        cmd: "nginx -p /erulb/server -c /erulb/conf/beta.conf"
        ports:
            - "80/tcp"
        network_mode: "host"
build:
    - "mkdir -p /erulb/server/logs"
